### ISSUE TITLE
Gdaemon cant correctly start HLDS

### ISSUE THREAD

**Issue by r4sas** [gameap/GDaemon2#9]
GD не может корректно запустить сервер на последних билдах на Debian 9.
HLDS выкачивался через steamcmd, но запустить его через GD не удается, при включенном `-debug` в output.txt пишет только следующее:
```
Error:libsteam_api.so: cannot open shared object file: No such file or directory
Unable to load engine, image is corrupt.
cat: hlds.32727.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Sat Mar 14 05:37:41 MSK 2020: Server restart in 10 seconds
```

В debug.log ничего нет.

При этом если из под юзера gameap вызывать сервер (`hlds_run -game cstrike ...`) то он запускается без проблем.

>Exe version 1.1.2.7/Stdio (cstrike)
>Exe build: 15:16:04 Jul 24 2019 (8308)

>gameap-daemon:
>  Installed: 2.1.0-252

**Comment by et-nik** [comment]
Проблема подтверждена.
Если запускать от gameap-starter без GameAP Daemon, то сервер тоже запускается.

Скорее всего проблема в переменных окружения, либо в LD_LIBRARY_PATH

**Comment by et-nik** [comment]
Проблема не наблюдается в версии 2.1.0-218
Выясняю причину.

Временное решение, удалить билд 252 и поставить 218:
```
service gameap-daemon stop
apt remove gameap-daemon
apt install gameap-daemon=2.1.0-218
service gameap-daemon start
```

**Comment by r4sas** [comment]
По этому поводу могу сказать только что GD переписывает где-то пути так, что вместо полноценного пишет `(null)`:
```
dlopen failed trying to load:
(null)/.steam/sdk32/steamclient.so
```

**Comment by et-nik** [comment]
Это из-за отсутствия `HOME` переменной окружения, было пофикшено в https://github.com/gameap/GDaemon2/issues/6

**Comment by afwn90cj93201nixr2e1re** [comment]
Нельзя сделать нормальный handle ошибок? Падает вообще где-то на map_base...

**Comment by afwn90cj93201nixr2e1re** [comment]
А, ну ясно, половина кода бусозависима...

**Comment by et-nik** [comment]
> Нельзя сделать нормальный handle ошибок? Падает вообще где-то на map_base...

По поводу map_base вот этот issue https://github.com/gameap/GDaemon2/issues/10

Handle ошибок можно сделать.
На бусте завязаны серверы (boost asio), в остальном буста почти нет.

**Comment by et-nik** [comment]
@r4sas 
Проблема исправлена вот здесь https://github.com/gameap/GDaemon2/commit/b19ac14006f3cddb8780466e979261ee278aac48

Для Debian 9 пересобрал пакет, нужно обновить:
```
apt update
apt install gameap-daemon
```

**Comment by r4sas** [comment]
Теперь сервер запускается. Спасибо.
